const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  SESSION_REQUEST: 'SESSION_REQUEST',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAILURE: 'SESSION_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  TICKET_REQUEST: 'TICKET_REQUEST',
  TICKET_SUCCESS: 'TICKET_SUCCESS',
  TICKET_FAILURE: 'TICKET_FAILURE',

  TICKET_INFO_REQUEST: 'TICKET_INFO_REQUEST',
  TICKET_INFO_SUCCESS: 'TICKET_INFO_SUCCESS',
  TICKET_INFO_FAILURE: 'TICKET_INFO_FAILURE',

  REFERENCE_CHANNEL_REQUEST: 'REFERENCE_CHANNEL_REQUEST',
  REFERENCE_CHANNEL_SUCCESS: 'REFERENCE_CHANNEL_SUCCESS',
  REFERENCE_CHANNEL_FAILURE: 'REFERENCE_CHANNEL_FAILURE',

  ERROR_INPUT: 'ERROR_INPUT',
};

export default actionTypes;
