const actionTypes = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  SESSION_REQUEST: 'SESSION_REQUEST',
  SESSION_SUCCESS: 'SESSION_SUCCESS',
  SESSION_FAILURE: 'SESSION_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  TASK_REQUEST: 'TASK_REQUEST',
  TASK_SUCCESS: 'TASK_SUCCESS',
  TASK_FAILURE: 'TASK_FAILURE',

  TASK_INFO_REQUEST: 'TASK_INFO_REQUEST',
  TASK_INFO_SUCCESS: 'TASK_INFO_REQUEST',
  TASK_INFO_FAILURE: 'TASK_INFO_REQUEST',

  ERROR_INPUT: 'ERROR_INPUT',
};

export default actionTypes;
