# Name of workflow
name: Omni

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build-lint-install:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [13.x]

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check install
        # Make install
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.dfbf37cc59b8a692d801b7b3ea1b7ed24854cf636d105d07f0978885fdba7c10}}
        with:
          coverageCommand: make lint
      - name: Check linter
        # Run Linter
        run: |
          make lint
        # Run Build
      - name: Check build
        run: |
          make build
